brand: _brand.yml

format:
  typst:
    toc: true
    toc-depth: 2
    number-sections: false
    fontsize: 11pt
    margin:
      x: 1.5in
      top: 1.2in
      bottom: 1in
    papersize: us-trade
    template: typst-template.typ
    tbl-colwidths: auto
  
  html:
    toc: true
  
  epub:
    toc: true